global:
  checkNewVersion: true
  sendAnonymousUsage: false
entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ':443'
    http:
      tls:
        certResolver: default
  traefik:
    address: ':8080'
providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    endpoint: 'tcp://dockersock-proxy:2375'
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false
    defaultRule: 'Host(`{{ trimSuffix `-config` .Name }}.{{ index .Labels "domain-base"}}`)'
api:
  insecure: true
  dashboard: true
log:
  filePath: /var/log/traefik.log
  level: ERROR
accessLog:
  filePath: /var/log/access.log
  bufferingSize: 0
  filters:
    statusCodes:
      - 400-499
    minDuration: 0s
certificatesResolvers:
  default:
    acme:
      email: ""
      storage: acme.json
      httpChallenge:
        entryPoint: http
